import type { Teacher, TeacherReview, LiveSession, CommunityPost, Conversation } from "./types";

// ─── Teachers ───────────────────────────────────────────
export const teachers: Teacher[] = [
  {
    id: "t1",
    userId: "u1",
    name: "Dr. Rafiq Hassan",
    title: "Senior Mathematics Instructor",
    bio: "Former BUET faculty with 14 years teaching advanced mathematics. I believe every student can master math with the right guidance. My approach combines conceptual understanding with rigorous problem-solving practice.",
    subjects: ["Mathematics", "Physics"],
    expertise: ["Calculus", "Linear Algebra", "Analytical Geometry", "Differential Equations", "Statistics"],
    education: "PhD Mathematics, BUET",
    certifications: ["BUET Faculty Member (2011-2020)", "National Math Olympiad Coach"],
    languages: ["English", "বাংলা"],
    hourlyRate: 2500,
    rating: 4.9,
    reviewCount: 312,
    totalStudents: 480,
    totalHours: 2840,
    yearsExperience: 14,
    isVerified: true,
    isAvailable: true,
    avatarUrl: "",
    teachingStyle: ["Interactive Problem Solving", "Concept-First Approach", "Exam-Focused Drills"],
    badge: "Top Rated",
  },
  {
    id: "t2",
    userId: "u2",
    name: "Farzana Akter",
    title: "Physics & Engineering Mentor",
    bio: "MIT graduate passionate about making physics intuitive. I use real-world analogies and visual explanations to help students see the beauty in physics. Let's explore the universe together.",
    subjects: ["Physics", "Mathematics"],
    expertise: ["Mechanics", "Thermodynamics", "Electromagnetism", "Optics", "Wave Theory"],
    education: "MSc Physics, MIT",
    certifications: ["MIT Teaching Fellowship", "Physics Olympiad Gold Medalist"],
    languages: ["English", "বাংলা"],
    hourlyRate: 2200,
    rating: 4.8,
    reviewCount: 245,
    totalStudents: 390,
    totalHours: 1950,
    yearsExperience: 10,
    isVerified: true,
    isAvailable: true,
    avatarUrl: "",
    teachingStyle: ["Visual Learning", "Real-World Analogies", "Socratic Method"],
    badge: "Most Booked",
  },
  {
    id: "t3",
    userId: "u3",
    name: "Nadia Rahman",
    title: "English Language & IELTS Coach",
    bio: "IELTS 8.5 scorer and certified English instructor. I specialize in helping students achieve their target scores through structured practice, personalized feedback, and confidence building.",
    subjects: ["English", "IELTS"],
    expertise: ["IELTS Preparation", "Academic Writing", "Reading Comprehension", "Grammar", "Speaking Fluency"],
    education: "MA English Literature, Dhaka University",
    certifications: ["IELTS Certified Trainer", "TESOL Certificate", "Cambridge CELTA"],
    languages: ["English", "বাংলা"],
    hourlyRate: 1800,
    rating: 4.9,
    reviewCount: 178,
    totalStudents: 520,
    totalHours: 2100,
    yearsExperience: 8,
    isVerified: true,
    isAvailable: true,
    avatarUrl: "",
    teachingStyle: ["Conversational Practice", "Structured Feedback", "Confidence Building"],
  },
  {
    id: "t4",
    userId: "u4",
    name: "Tanvir Ahmed",
    title: "Biology & Medical Prep Specialist",
    bio: "MBBS from BSMMU with a passion for teaching biology. I make complex biological concepts simple and help students prepare effectively for medical admission exams.",
    subjects: ["Biology", "Chemistry"],
    expertise: ["Genetics", "Ecology", "Human Physiology", "Biochemistry", "Medical Entrance Prep"],
    education: "MBBS, Bangabandhu Sheikh Mujib Medical University",
    certifications: ["Medical Board Certified", "Biology Olympiad Coach"],
    languages: ["English", "বাংলা"],
    hourlyRate: 1900,
    rating: 4.7,
    reviewCount: 156,
    totalStudents: 290,
    totalHours: 1450,
    yearsExperience: 7,
    isVerified: true,
    isAvailable: false,
    avatarUrl: "",
    teachingStyle: ["Case-Based Learning", "Visual Diagrams", "Exam Strategy"],
  },
  {
    id: "t5",
    userId: "u5",
    name: "Sarah Chen",
    title: "Full-Stack Programming Instructor",
    bio: "Senior Software Engineer at a Fortune 500 company. I teach programming through building real projects. From Python basics to React applications — let's build something amazing together.",
    subjects: ["Programming", "Data Analytics"],
    expertise: ["Python", "JavaScript", "React", "Node.js", "SQL", "Data Analysis"],
    education: "BSc Computer Science, Stanford University",
    certifications: ["AWS Solutions Architect", "Google Cloud Professional"],
    languages: ["English"],
    hourlyRate: 3000,
    rating: 4.8,
    reviewCount: 203,
    totalStudents: 340,
    totalHours: 1680,
    yearsExperience: 9,
    isVerified: true,
    isAvailable: true,
    avatarUrl: "",
    teachingStyle: ["Project-Based Learning", "Pair Programming", "Code Review"],
    badge: "New on Platform",
  },
  {
    id: "t6",
    userId: "u6",
    name: "Prof. Karim Uddin",
    title: "Chemistry Expert & Researcher",
    bio: "PhD in Organic Chemistry from Dhaka University with 12 years of teaching experience. I focus on building deep conceptual understanding through experiments and real-world applications.",
    subjects: ["Chemistry"],
    expertise: ["Organic Chemistry", "Inorganic Chemistry", "Physical Chemistry", "Analytical Chemistry"],
    education: "PhD Organic Chemistry, University of Dhaka",
    certifications: ["Royal Society of Chemistry Member", "National Science Award 2019"],
    languages: ["English", "বাংলা"],
    hourlyRate: 2000,
    rating: 4.6,
    reviewCount: 189,
    totalStudents: 310,
    totalHours: 1860,
    yearsExperience: 12,
    isVerified: true,
    isAvailable: true,
    avatarUrl: "",
    teachingStyle: ["Experimental Approach", "Molecular Visualization", "Conceptual Depth"],
  },
];

// ─── Live Sessions ──────────────────────────────────────
const now = Date.now();
const hour = 3600000;
const day = 86400000;

export const liveSessions: LiveSession[] = [
  {
    id: "s1",
    teacherId: "t1",
    teacherName: "Dr. Rafiq Hassan",
    teacherAvatar: "",
    title: "Mastering Integration by Parts",
    subject: "Mathematics",
    description: "Deep dive into integration techniques — by parts, substitution, and partial fractions. Bring your toughest problems!",
    scheduledAt: new Date(now + 2 * hour),
    durationMinutes: 60,
    maxStudents: 8,
    enrolledCount: 5,
    enrolledStudentIds: [],
    status: "scheduled",
    meetingCode: "VT-MATH-001",
    sessionType: "small-group",
    price: 1500,
  },
  {
    id: "s2",
    teacherId: "t2",
    teacherName: "Farzana Akter",
    teacherAvatar: "",
    title: "Physics: Thermodynamics Masterclass",
    subject: "Physics",
    description: "Understanding entropy, enthalpy, and the laws of thermodynamics through real-world examples and practice problems.",
    scheduledAt: new Date(now + 5 * hour),
    durationMinutes: 90,
    maxStudents: 12,
    enrolledCount: 8,
    enrolledStudentIds: [],
    status: "scheduled",
    meetingCode: "VT-PHY-002",
    sessionType: "small-group",
    price: 1200,
  },
  {
    id: "s3",
    teacherId: "t3",
    teacherName: "Nadia Rahman",
    teacherAvatar: "",
    title: "IELTS Speaking Practice Session",
    subject: "English",
    description: "Practice IELTS Speaking Part 2 & 3 with personalized feedback. Record and review your responses with expert guidance.",
    scheduledAt: new Date(now + 24 * hour),
    durationMinutes: 45,
    maxStudents: 1,
    enrolledCount: 0,
    enrolledStudentIds: [],
    status: "scheduled",
    meetingCode: "VT-ENG-003",
    sessionType: "1-to-1",
    price: 1800,
  },
  {
    id: "s4",
    teacherId: "t5",
    teacherName: "Sarah Chen",
    teacherAvatar: "",
    title: "Build a React App from Scratch",
    subject: "Programming",
    description: "Hands-on workshop: build a complete React application from zero. Learn components, state, hooks, and deployment.",
    scheduledAt: new Date(now + 48 * hour),
    durationMinutes: 120,
    maxStudents: 6,
    enrolledCount: 3,
    enrolledStudentIds: [],
    status: "scheduled",
    meetingCode: "VT-PRG-004",
    sessionType: "small-group",
    price: 2500,
  },
  {
    id: "s5",
    teacherId: "t6",
    teacherName: "Prof. Karim Uddin",
    teacherAvatar: "",
    title: "Organic Chemistry: Reaction Mechanisms",
    subject: "Chemistry",
    description: "Master organic reaction mechanisms — SN1, SN2, E1, E2. Visualize molecules and understand electron flow.",
    scheduledAt: new Date(now + 72 * hour),
    durationMinutes: 60,
    maxStudents: 10,
    enrolledCount: 4,
    enrolledStudentIds: [],
    status: "scheduled",
    meetingCode: "VT-CHE-005",
    sessionType: "small-group",
    price: 1300,
  },
];

// ─── Reviews ────────────────────────────────────────────
export const teacherReviews: TeacherReview[] = [
  { id: "r1", studentName: "Tanvir H.", rating: 5, comment: "Dr. Rafiq made calculus finally click for me. His step-by-step approach and patience are incredible. Went from struggling to confident in 3 weeks.", subject: "Mathematics", createdAt: "2 weeks ago" },
  { id: "r2", studentName: "Nusrat J.", rating: 5, comment: "Farzana's physics explanations are the best I've ever heard. She uses real-world examples that make abstract concepts tangible.", subject: "Physics", createdAt: "1 week ago" },
  { id: "r3", studentName: "Arif C.", rating: 5, comment: "My IELTS speaking score improved from 6.0 to 7.5 after just 5 sessions with Nadia. Her feedback is incredibly detailed and actionable.", subject: "English", createdAt: "3 days ago" },
  { id: "r4", studentName: "Sabrina M.", rating: 4, comment: "Great teaching style. The live coding sessions with Sarah are extremely practical. I built my first full-stack app in the course.", subject: "Programming", createdAt: "5 days ago" },
  { id: "r5", studentName: "Imran K.", rating: 5, comment: "Prof. Karim's chemistry visualization techniques helped me understand organic mechanisms that I'd been struggling with for months.", subject: "Chemistry", createdAt: "1 day ago" },
];

// ─── Community Posts ────────────────────────────────────
export const communityPosts: CommunityPost[] = [
  {
    id: "p1",
    authorId: "u1",
    authorName: "Dr. Rafiq Hassan",
    authorRole: "teacher",
    authorAvatar: "",
    title: "5 Tips for Mastering Calculus Integration",
    content: "Integration doesn't have to be intimidating. Here are 5 techniques that will transform your approach:\n\n1. **Recognize the pattern** — before computing, identify which method fits\n2. **Practice substitution** — it solves 60% of integration problems\n3. **Learn integration by parts deeply** — it's the Swiss Army knife\n4. **Draw the area** — visualize what you're integrating\n5. **Check by differentiating** — always verify your answer\n\nJoin my live session this week to practice these together!",
    subject: "Mathematics",
    tags: ["calculus", "integration", "tips"],
    likesCount: 47,
    repliesCount: 12,
    createdAt: new Date(now - day),
  },
  {
    id: "p2",
    authorId: "u2",
    authorName: "Farzana Akter",
    authorRole: "teacher",
    authorAvatar: "",
    title: "Why Understanding > Memorizing in Physics",
    content: "I see too many students memorizing formulas without understanding the physics behind them. Here's my approach:\n\nEvery formula tells a story. F=ma isn't just letters — it's the relationship between force, mass, and acceleration that governs everything from falling apples to orbiting planets.\n\nWhen you understand the story, you don't need to memorize. The formula becomes obvious.\n\nCome to my Thermodynamics Masterclass to experience this approach firsthand.",
    subject: "Physics",
    tags: ["physics", "learning", "conceptual"],
    likesCount: 38,
    repliesCount: 8,
    createdAt: new Date(now - 2 * day),
  },
  {
    id: "p3",
    authorId: "u10",
    authorName: "Tanvir H.",
    authorRole: "student",
    authorAvatar: "",
    title: "How I improved my Math score from 45% to 89%",
    content: "I wanted to share my journey for anyone struggling with math like I was.\n\n3 months ago, I couldn't solve a basic integration problem. Today, I scored 89% in my mock exam.\n\nWhat changed:\n- Started attending Dr. Rafiq's live sessions\n- Practiced daily using the AI tutor for quick help\n- Kept a mistake book and reviewed it weekly\n- Asked questions during class (even the \"stupid\" ones)\n\nThe biggest lesson: asking questions isn't a sign of weakness — it's the fastest way to learn.",
    tags: ["math", "progress", "motivation"],
    likesCount: 62,
    repliesCount: 18,
    createdAt: new Date(now - 3 * day),
  },
];

// ─── Conversations ──────────────────────────────────────
export const conversations: Conversation[] = [
  { id: "c1", participants: ["me", "t1"], participantNames: ["Dr. Rafiq Hassan"], lastMessage: "See you in class tomorrow! Don't forget to review Chapter 5.", lastMessageAt: new Date(now - hour), unreadCount: 1 },
  { id: "c2", participants: ["me", "t3"], participantNames: ["Nadia Rahman"], lastMessage: "Great progress on your IELTS practice test!", lastMessageAt: new Date(now - 3 * hour), unreadCount: 0 },
  { id: "c3", participants: ["me", "t5"], participantNames: ["Sarah Chen"], lastMessage: "I've pushed the code review feedback to your repo.", lastMessageAt: new Date(now - day), unreadCount: 2 },
];

// ─── Available Subjects for Search ──────────────────────
export const subjects = [
  { name: "Mathematics", icon: "📐", count: 12 },
  { name: "Physics", icon: "⚡", count: 8 },
  { name: "Chemistry", icon: "🧪", count: 6 },
  { name: "English", icon: "📖", count: 10 },
  { name: "Biology", icon: "🧬", count: 5 },
  { name: "Programming", icon: "💻", count: 15 },
  { name: "IELTS", icon: "🎯", count: 7 },
  { name: "Data Analytics", icon: "📊", count: 4 },
  { name: "Business", icon: "📈", count: 3 },
  { name: "Design", icon: "🎨", count: 2 },
];

// ─── Session Types ──────────────────────────────────────
export const sessionTypes = [
  { value: "1-to-1", label: "1-on-1 Session", description: "Personalized attention just for you" },
  { value: "small-group", label: "Small Group", description: "Learn with 3-8 peers" },
  { value: "trial", label: "Trial Class", description: "Try before you commit" },
  { value: "mentoring", label: "Mentoring", description: "Long-term learning guidance" },
  { value: "exam-prep", label: "Exam Preparation", description: "Focused test prep" },
  { value: "project-help", label: "Project Help", description: "Hands-on project assistance" },
];
